### PR TITLE
Fix index out of bounds error in another arm of the match statement

### PR DESCRIPTION
**Pull request by hpeebles**

### CODE REVIEW

**Comment by hpeebles** [comment]
This uses exactly the same pattern as my previous commit, but this time it fixes the `(Some (before), Some (after)) =>` branch of the match statement.

**Comment by spearman** [comment]
Thanks again!

**Comment by hpeebles** [comment]
Could you make a new crate version with this commit please!

**Comment by spearman** [comment]
Published https://crates.io/crates/range-set/0.0.7

**Pull request merged**
